name: Daily Commit

# Define the schedule with cron syntax to run once per day at 00:00 UTC
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  add-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make changes
      run: |
        # Add your commands here to modify files or update documentation
        echo "Daily update" >> daily_update.txt

    - name: Commit changes with email 24ds2000116@ds.study.iitm.ac.in
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '24ds2000116@ds.study.iitm.ac.in'
        git add .
        git commit -m "Daily automated update"
        git push

# Note: You might need to set up a personal access token with write permissions
# and add it as a secret in your repository to allow the action to push changes.
# For example, you can name the secret `GH_TOKEN` and use it as follows:

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git push
