name: Sample GitHub Action

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24ds2000116@ds.study.iitm.ac.in
        run: echo "Hello, world!"
